name: Maven Backend Test on PR

on: [pull_request]

jobs: 
    build:
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres:latest
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: test_db
                ports:
                    - 5234:5234
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            
            - name: Setup JDK
              uses: action/setup-java@v2
              with:
                java-version: "17"
                distribution: "temurin"
            
            - name: Build and run tests
              run: mvn -f Backend/pom.xml clean install